---
- hosts: all
  become: yes
  tasks:
    - name: install nginx on prod server
      apt:
       name: apache2
       state: present 
    
    - name: start the apache2 server 
      servvice:
        name: apache2
        state: started 